export interface AgentDef {
  id: string; name: string; icon: string; color: string
  category: 'strategy'|'implementation'|'quality'|'operations'
  description: string; soulPrompt: string; skills: string[]
  toolPolicy: 'ask'|'record'|'ignore'; allowedTools: string[]; deniedTools: string[]
  computerAccess: { shell: boolean; fileRead: boolean; fileWrite: boolean; browser: boolean; canvas: boolean; cron: boolean; network: boolean }
}
export const AGENTS: Record<string, AgentDef> = {
  planner: { id:'planner', name:'Planner', icon:'📐', color:'#C8A74B', category:'strategy', description:'Phased implementation blueprints', soulPrompt:'You are DOGMA Robotics senior planner. Create phased blueprints for a 27-DOF biomimetic robotic hand startup. Decompose into phases, tasks, dependencies, timeline, risks.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['system.run','browser.*','file.*','web_search'], deniedTools:['system.run:rm -rf*'], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:true,cron:false,network:true} },
  architect: { id:'architect', name:'Architect', icon:'🏗️', color:'#3A5A7A', category:'strategy', description:'Technology decisions and system design', soulPrompt:'You are DOGMA Robotics systems architect. Define bounded contexts, data flows, ADRs. Every decision needs a rationale.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['system.run','browser.*','file.*','web_search'], deniedTools:['system.run:rm -rf*'], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:true,cron:false,network:true} },
  researcher: { id:'researcher', name:'Researcher', icon:'🔍', color:'#3A7A7A', category:'strategy', description:'Deep research with real browser access', soulPrompt:'You are DOGMA Robotics research agent. ALWAYS search before recommending. Use browser for SOTA, papers, competitors.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['browser.*','file.*','web_search'], deniedTools:['system.run:rm*'], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:false,cron:false,network:true} },
  coder: { id:'coder', name:'Coder', icon:'💻', color:'#2D7A5D', category:'implementation', description:'Full-stack dev with shell + browser on your machine', soulPrompt:'You are DOGMA Robotics senior full-stack dev with machine access. TDD: read code, write test, implement, run tests, refactor. TypeScript strict, no any.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['system.run','file.*','browser.*','canvas.*'], deniedTools:[], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:true,cron:false,network:true} },
  'data-engineer': { id:'data-engineer', name:'Data Eng', icon:'🗄️', color:'#3A7A7A', category:'implementation', description:'Schemas, migrations, SQL', soulPrompt:'You are DOGMA Robotics data engineer. Design schemas, write migrations, optimize queries. Can run psql.', skills:['dogma-context'], toolPolicy:'ask', allowedTools:['system.run','file.*'], deniedTools:['system.run:DROP DATABASE*'], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:false,canvas:false,cron:false,network:true} },
  tester: { id:'tester', name:'Tester', icon:'🧪', color:'#8A3333', category:'quality', description:'Writes and runs tests on your machine', soulPrompt:'You are DOGMA Robotics QA. Write AND run tests. Never write tests without executing them.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['system.run','file.*','browser.*'], deniedTools:[], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:false,cron:false,network:true} },
  reviewer: { id:'reviewer', name:'Reviewer', icon:'👁️', color:'#A78530', category:'quality', description:'Code review with codebase access (read-only)', soulPrompt:'You are DOGMA Robotics code reviewer. Read files, run linters, check types. Score: Architecture, Quality, Tests, Security (1-5 each).', skills:['dogma-context'], toolPolicy:'record', allowedTools:['system.run:cat*','system.run:grep*','system.run:find*','file.read*'], deniedTools:['file.write*'], computerAccess:{shell:true,fileRead:true,fileWrite:false,browser:false,canvas:false,cron:false,network:false} },
  'security-scanner': { id:'security-scanner', name:'Security', icon:'🔒', color:'#8A3333', category:'quality', description:'npm audit, secret scanning, vulnerability reports', soulPrompt:'You are DOGMA Robotics security engineer. Run npm audit, grep for secrets, review auth flows. CVSS-scored reports.', skills:['dogma-context'], toolPolicy:'ask', allowedTools:['system.run','file.read*','browser.*'], deniedTools:['file.write*'], computerAccess:{shell:true,fileRead:true,fileWrite:false,browser:true,canvas:false,cron:false,network:true} },
  documenter: { id:'documenter', name:'Documenter', icon:'📄', color:'#3A5A7A', category:'operations', description:'Polished HTML reports and docs as real files', soulPrompt:'You are DOGMA Robotics tech writer. Write files to disk: HTML, Markdown, CSV. DOGMA branding: navy bg, gold accents.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['file.*','browser.*'], deniedTools:[], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:true,canvas:true,cron:false,network:false} },
  coordinator: { id:'coordinator', name:'Coordinator', icon:'🎯', color:'#C8A74B', category:'operations', description:'Synthesizes multi-agent outputs', soulPrompt:'You are the Swarm Coordinator. Read ALL agent outputs, resolve conflicts, 5-7 bullet executive summary. Never concatenate — synthesize.', skills:['dogma-context'], toolPolicy:'record', allowedTools:['file.*'], deniedTools:[], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:false,canvas:true,cron:false,network:false} },
  devops: { id:'devops', name:'DevOps', icon:'🚀', color:'#2D7A5D', category:'operations', description:'CI/CD, deployment, Docker', soulPrompt:'You are DOGMA Robotics DevOps. Manage deployments, Docker, CI/CD. Validate before applying. Rolling deploys.', skills:['dogma-context'], toolPolicy:'ask', allowedTools:['system.run','file.*'], deniedTools:[], computerAccess:{shell:true,fileRead:true,fileWrite:true,browser:false,canvas:false,cron:true,network:true} },
}
export function getAgentList() { return Object.values(AGENTS).map(a=>({id:a.id,name:a.name,icon:a.icon,color:a.color,category:a.category,description:a.description,computerAccess:a.computerAccess})) }
